/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMeta"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The demo identities. Open, because one has to be picked before anything else can be asked. */
        get: operations["listUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/matters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listMatters"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/matters/{matterId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                matterId: components["parameters"]["matterId"];
            };
            cookie?: never;
        };
        get: operations["getMatter"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/matters/{matterId}/parties": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                matterId: components["parameters"]["matterId"];
            };
            cookie?: never;
        };
        get: operations["listParties"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/matters/{matterId}/documents": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                matterId: components["parameters"]["matterId"];
            };
            cookie?: never;
        };
        get: operations["listDocuments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/matters/{matterId}/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                matterId: components["parameters"]["matterId"];
            };
            cookie?: never;
        };
        get: operations["listEvidence"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/matters/{matterId}/risks": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                matterId: components["parameters"]["matterId"];
            };
            cookie?: never;
        };
        get: operations["listRisks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/matters/{matterId}/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                matterId: components["parameters"]["matterId"];
            };
            cookie?: never;
        };
        get: operations["listTasks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/matters/{matterId}/events": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                matterId: components["parameters"]["matterId"];
            };
            cookie?: never;
        };
        get: operations["listEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/risks/{riskId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                riskId: string;
            };
            cookie?: never;
        };
        get: operations["getRisk"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/saved-views": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listSavedViews"];
        put?: never;
        post: operations["createSavedView"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/saved-views/{viewId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                viewId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteSavedView"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/actions/propose-risk-disposition": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["proposeRiskDisposition"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/actions/decide-risk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["decideRisk"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/actions/return-risk-proposal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["returnRiskProposal"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/actions/assign-reviewer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["assignReviewer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/action-attempts/{attemptId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attemptId: string;
            };
            cookie?: never;
        };
        /** @description What the backend knows about one attempt. 404 means the attempt never arrived, so the same key may be sent again. */
        get: operations["getActionAttempt"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{jobId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobId: string;
            };
            cookie?: never;
        };
        get: operations["getJob"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        User: components["schemas"]["schemas-User"] & {
            role?: components["schemas"]["Role"];
        };
        Affordance: components["schemas"]["schemas-Affordance"] & {
            type?: components["schemas"]["ActionType"];
        };
        /** @enum {string} */
        ObjectKind: "matter" | "risk" | "document" | "evidence" | "task";
        ObjectRef: components["schemas"]["schemas-ObjectRef"] & {
            kind?: components["schemas"]["ObjectKind"];
        };
        /** @enum {string} */
        AuditEventType: "matter-opened" | "document-received" | "document-version-added" | "evidence-registered" | "risk-registered" | "disposition-proposed" | "proposal-returned" | "risk-decided" | "reviewer-assigned" | "task-created";
        AuditEvent: components["schemas"]["schemas-AuditEvent"] & {
            type?: components["schemas"]["AuditEventType"];
            target?: components["schemas"]["ObjectRef"];
        };
        /** @enum {string} */
        Role: "partner" | "associate" | "paralegal";
        /** @enum {string} */
        ActionType: "propose-risk-disposition" | "decide-risk" | "return-risk-proposal" | "assign-reviewer";
        /** @enum {string} */
        MatterStatus: "active" | "on-hold" | "closed";
        /** @enum {string} */
        MatterStage: "intake" | "pleading" | "evidence" | "hearing" | "enforcement";
        /**
         * @default deadline
         * @enum {string}
         */
        MatterSort: "deadline" | "-deadline" | "updatedAt" | "-updatedAt";
        MatterFields: {
            id: string;
            title: string;
            cause: string;
            client: string;
            counterparty: string;
            stage: components["schemas"]["MatterStage"];
            status: components["schemas"]["MatterStatus"];
            owner: components["schemas"]["UserRef"];
            reviewer: components["schemas"]["UserRef"] | null;
            nextDeadline: {
                label: string;
                /** Format: date */
                date: string;
            } | null;
            /** @description Risks in state open or proposed */
            openRisks: number;
            highOpenRisks: number;
            /** @description Risks whose standing proposal or decision cites superseded evidence */
            recheckRisks: number;
            version: number;
            /** Format: date-time */
            updatedAt: string;
        };
        MatterSummary: components["schemas"]["MatterFields"];
        MatterPage: {
            items: components["schemas"]["MatterSummary"][];
            total: number;
            page: number;
            pageSize: number;
            actions: components["schemas"]["Affordance"][];
        };
        Matter: components["schemas"]["MatterFields"] & {
            court: string | null;
            caseNumber: string | null;
            /** Format: date */
            openedAt: string;
            links: {
                parties: number;
                documents: number;
                evidence: number;
                risks: number;
                tasks: number;
            };
        };
        Party: {
            id: string;
            name: string;
            /** @enum {string} */
            role: "client" | "counterparty" | "opposing-counsel" | "court";
            /** @enum {string} */
            kind: "organization" | "person";
        };
        Document: {
            id: string;
            title: string;
            /** @enum {string} */
            kind: "contract" | "correspondence" | "exhibit" | "pleading" | "memo";
            /** @description Current version */
            version: number;
            /** Format: date */
            receivedAt: string;
            source: string;
            privileged: boolean;
            evidenceCount: number;
        };
        /** @enum {string} */
        Stance: "supports" | "refutes" | "limits";
        Evidence: {
            id: string;
            matterId: string;
            document: {
                id: string;
                title: string;
                /** @description Current version of the document */
                version: number;
            };
            /** @description The version this evidence was taken from */
            documentVersion: number;
            /** @description False when the document has a newer version */
            basisCurrent: boolean;
            /** @description True when the actor may know it exists but not read it */
            restricted: boolean;
            locator: string | null;
            excerpt: string | null;
            risks: {
                id: string;
                title: string;
                stance: components["schemas"]["Stance"];
            }[];
        };
        /** @enum {string} */
        Severity: "high" | "medium" | "low";
        /** @enum {string} */
        RiskStatus: "open" | "proposed" | "decided";
        /** @enum {string} */
        Disposition: "accept" | "mitigate" | "escalate";
        RiskFields: {
            id: string;
            matterId: string;
            title: string;
            /** @enum {string} */
            category: "limitation" | "evidence" | "performance" | "procedure";
            severity: components["schemas"]["Severity"];
            status: components["schemas"]["RiskStatus"];
            /** @description Set once decided */
            disposition: components["schemas"]["Disposition"] | null;
            /** @description A recorded proposal or decision cites evidence whose document has since changed */
            needsRecheck: boolean;
            evidenceCount: number;
            version: number;
            /** Format: date-time */
            updatedAt: string;
        };
        RiskSummary: components["schemas"]["RiskFields"];
        DispositionRecord: {
            /** @enum {string} */
            kind: "proposal" | "decision" | "return";
            by: components["schemas"]["UserRef"];
            /** Format: date-time */
            at: string;
            attemptId: string;
            disposition?: components["schemas"]["Disposition"];
            rationale?: string;
            cited?: {
                evidenceId: string;
                documentVersion: number;
                basisCurrent: boolean;
            }[];
        };
        Risk: components["schemas"]["RiskFields"] & {
            statement: string;
            matterTitle: string;
            /** @description The step this risk is waiting for and who holds it. Null when nothing is pending. */
            next: {
                /** @enum {string} */
                step: "propose" | "decide" | "redecide";
                /** @description Null when the role that holds the step has nobody assigned */
                owner: components["schemas"]["UserRef"] | null;
            } | null;
            evidence: {
                stance: components["schemas"]["Stance"];
                item: components["schemas"]["Evidence"];
            }[];
            /** @description Proposals, returns and the decision, oldest first. Nothing is overwritten. */
            records: components["schemas"]["DispositionRecord"][];
            actions: components["schemas"]["Affordance"][];
        };
        Task: {
            id: string;
            matterId: string;
            title: string;
            /** @enum {string} */
            kind: "review" | "follow-up" | "filing";
            assignee: components["schemas"]["UserRef"];
            /** Format: date */
            dueDate: string;
            /** @enum {string} */
            status: "open" | "done";
            origin: {
                attemptId: string;
                /** @description The object the originating action was about */
                ref: string;
            } | null;
        };
        MatterQuery: {
            q?: string;
            status?: components["schemas"]["MatterStatus"];
            stage?: components["schemas"]["MatterStage"];
            reviewer?: string;
            openRisk?: boolean;
            sort?: components["schemas"]["MatterSort"];
        };
        SavedViewInput: {
            name: string;
            query: components["schemas"]["MatterQuery"];
        };
        SavedView: {
            id: string;
            name: string;
            query: components["schemas"]["MatterQuery"];
            /** @description Shared views belong to the team and cannot be deleted here */
            shared: boolean;
            owner: components["schemas"]["UserRef"] | null;
        };
        DispositionInput: {
            riskId: string;
            expectedVersion: number;
            disposition: components["schemas"]["Disposition"];
            rationale: string;
            citedEvidenceIds: string[];
        };
        ReturnInput: {
            riskId: string;
            expectedVersion: number;
            rationale: string;
        };
        AssignReviewerInput: {
            matterIds: string[];
            reviewerId: string;
        };
        SearchHit: {
            /** @enum {string} */
            kind: "matter" | "risk";
            id: string;
            title: string;
            matterId: string;
            context: string;
        };
        RuleViolation: {
            rule: string;
            ruleVersion: number;
            message: string;
            /** @description Who may grant an exception */
            exceptionOwner?: string;
            /** @description The object the violation is about */
            ref?: string;
        };
        UserRef: {
            id: string;
            name: string;
        };
        Problem: {
            /** @enum {string} */
            code: "unauthenticated" | "forbidden" | "not-found" | "conflict" | "rule-violation" | "invalid-input" | "unavailable";
            message: string;
            violations?: components["schemas"]["RuleViolation"][];
            /** @description On conflict */
            currentVersion?: number;
            changedBy?: components["schemas"]["UserRef"];
            /** Format: date-time */
            changedAt?: string;
            /** @description Who to ask when access is refused */
            contact?: string;
        };
        Meta: {
            /** @enum {string} */
            environment: "synthetic-demo" | "production";
            dataNotice: string;
            contractVersion: string;
            scenario: string;
        };
        "schemas-User": {
            id: string;
            name: string;
            /** @description A role name defined by the scenario */
            role: string;
            /** @description True when this user can be chosen as a demo identity */
            demoPersona: boolean;
        };
        "schemas-Affordance": {
            /** @description An action type defined by the scenario */
            type: string;
            allowed: boolean;
            violations: components["schemas"]["RuleViolation"][];
        };
        "schemas-ObjectRef": {
            /** @description An object kind defined by the scenario */
            kind: string;
            id: string;
            title: string;
        };
        "schemas-AuditEvent": {
            id: string;
            /** @description The object whose record this event belongs to */
            subjectId: string;
            /** Format: date-time */
            at: string;
            actor: components["schemas"]["UserRef"];
            /** @description An event type defined by the scenario */
            type: string;
            target: components["schemas"]["schemas-ObjectRef"];
            /** @description Version of the target after the event */
            targetVersion: number | null;
            attemptId: string | null;
            changes: {
                field: string;
                from: string | null;
                to: string | null;
            }[];
            /** @description Rules checked */
            rules: string[];
            note: string | null;
        };
        ActionResult: {
            attemptId: string;
            type: string;
            target: components["schemas"]["schemas-ObjectRef"];
            targetVersion: number;
            eventIds: string[];
            created: components["schemas"]["schemas-ObjectRef"][];
        };
        JobItem: {
            ref: components["schemas"]["schemas-ObjectRef"];
            /** @enum {string} */
            status: "pending" | "applied" | "rejected";
            violations: components["schemas"]["RuleViolation"][];
        };
        Job: {
            id: string;
            attemptId: string;
            type: string;
            /** @enum {string} */
            status: "running" | "completed";
            total: number;
            done: number;
            items: components["schemas"]["JobItem"][];
        };
        ActionAttempt: {
            attemptId: string;
            type: string;
            actor: components["schemas"]["UserRef"];
            /** Format: date-time */
            receivedAt: string;
            /**
             * @description For a job action, applied means the job ran to the end; whether each item took effect is in the job's items, not here.
             * @enum {string}
             */
            outcome: "applied" | "rejected" | "running";
            result?: components["schemas"]["ActionResult"];
            problem?: components["schemas"]["Problem"];
            jobId?: string;
        };
    };
    responses: {
        /** @description Why the request was not served */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Problem"];
            };
        };
        /** @description The action took effect */
        ActionApplied: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ActionResult"];
            };
        };
    };
    parameters: {
        matterId: string;
        /** @description Identity of this attempt. Sending the same key again returns the first result. */
        idempotencyKey: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getMeta: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Environment the backend reports */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Meta"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current actor */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    listUsers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Users */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"][];
                };
            };
            401: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    search: {
        parameters: {
            query: {
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Objects the actor may see */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchHit"][];
                };
            };
            401: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    listMatters: {
        parameters: {
            query?: {
                q?: string;
                status?: components["schemas"]["MatterStatus"];
                stage?: components["schemas"]["MatterStage"];
                /** @description A user id, "me" for the current actor, or "none" for unassigned */
                reviewer?: string;
                /** @description Only matters with risks awaiting disposition */
                openRisk?: boolean;
                sort?: components["schemas"]["MatterSort"];
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of matters */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatterPage"];
                };
            };
            401: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    getMatter: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                matterId: components["parameters"]["matterId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Matter */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Matter"];
                };
            };
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    listParties: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                matterId: components["parameters"]["matterId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Parties */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Party"][];
                };
            };
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    listDocuments: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                matterId: components["parameters"]["matterId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Documents */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Document"][];
                };
            };
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    listEvidence: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                matterId: components["parameters"]["matterId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Evidence */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Evidence"][];
                };
            };
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    listRisks: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                matterId: components["parameters"]["matterId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Risks */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RiskSummary"][];
                };
            };
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    listTasks: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                matterId: components["parameters"]["matterId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tasks */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"][];
                };
            };
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    listEvents: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                matterId: components["parameters"]["matterId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Audit events */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditEvent"][];
                };
            };
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    getRisk: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                riskId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Risk with its evidence */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Risk"];
                };
            };
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    listSavedViews: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Shared views and the actor's own */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedView"][];
                };
            };
            401: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    createSavedView: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SavedViewInput"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedView"];
                };
            };
            401: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    deleteSavedView: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                viewId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    proposeRiskDisposition: {
        parameters: {
            query?: never;
            header: {
                /** @description Identity of this attempt. Sending the same key again returns the first result. */
                "Idempotency-Key": components["parameters"]["idempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DispositionInput"];
            };
        };
        responses: {
            200: components["responses"]["ActionApplied"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    decideRisk: {
        parameters: {
            query?: never;
            header: {
                /** @description Identity of this attempt. Sending the same key again returns the first result. */
                "Idempotency-Key": components["parameters"]["idempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DispositionInput"];
            };
        };
        responses: {
            200: components["responses"]["ActionApplied"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    returnRiskProposal: {
        parameters: {
            query?: never;
            header: {
                /** @description Identity of this attempt. Sending the same key again returns the first result. */
                "Idempotency-Key": components["parameters"]["idempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReturnInput"];
            };
        };
        responses: {
            200: components["responses"]["ActionApplied"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    assignReviewer: {
        parameters: {
            query?: never;
            header: {
                /** @description Identity of this attempt. Sending the same key again returns the first result. */
                "Idempotency-Key": components["parameters"]["idempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignReviewerInput"];
            };
        };
        responses: {
            /** @description Accepted as a job; each matter is checked and applied on its own */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            403: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    getActionAttempt: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attemptId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Attempt */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionAttempt"];
                };
            };
            404: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    getJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Job */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            404: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
}
