/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMeta"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The demo identities. Open, because one has to be picked before anything else can be asked. */
        get: operations["listUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listCases"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cases/{caseId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                caseId: components["parameters"]["caseId"];
            };
            cookie?: never;
        };
        get: operations["getCase"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cases/{caseId}/checks": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                caseId: components["parameters"]["caseId"];
            };
            cookie?: never;
        };
        /** @description The drill rules evaluated against the current versions of the case's files. */
        get: operations["listChecks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cases/{caseId}/proposal": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                caseId: components["parameters"]["caseId"];
            };
            cookie?: never;
        };
        get: operations["getProposal"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cases/{caseId}/events": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                caseId: components["parameters"]["caseId"];
            };
            cookie?: never;
        };
        get: operations["listEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/files/{fileId}/versions/{version}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                fileId: string;
                version: number;
            };
            cookie?: never;
        };
        /** @description One version of a file, with the fragments that checks and records point at. */
        get: operations["getFileVersion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/actions/submit-for-review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["submitForReview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/actions/accept-review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["acceptReview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/actions/return-review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["returnReview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/action-attempts/{attemptId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attemptId: string;
            };
            cookie?: never;
        };
        /** @description What the backend knows about one attempt. 404 means the attempt never arrived, so the same key may be sent again. */
        get: operations["getActionAttempt"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        Role: "reviewer" | "lead" | "observer";
        User: components["schemas"]["schemas-User"] & {
            role?: components["schemas"]["Role"];
        };
        /** @enum {string} */
        ActionType: "submit-for-review" | "accept-review" | "return-review";
        Affordance: components["schemas"]["schemas-Affordance"] & {
            type?: components["schemas"]["ActionType"];
        };
        /** @enum {string} */
        ObjectKind: "case" | "file";
        ObjectRef: components["schemas"]["schemas-ObjectRef"] & {
            kind?: components["schemas"]["ObjectKind"];
        };
        /** @enum {string} */
        AuditEventType: "case-opened" | "file-received" | "file-version-added" | "review-submitted" | "review-returned" | "review-accepted";
        AuditEvent: components["schemas"]["schemas-AuditEvent"] & {
            type?: components["schemas"]["AuditEventType"];
            target?: components["schemas"]["ObjectRef"];
        };
        /** @description An exact amount. `minor` counts the currency's smallest unit; an unknown amount is null, never zero. */
        Money: {
            currency: string;
            minor: number;
        };
        /**
         * @description Business state. needs-material and ready are both before submission and follow from the checks; in-review and decided follow from the records.
         * @enum {string}
         */
        CaseStatus: "needs-material" | "ready" | "in-review" | "decided";
        /**
         * @default dueDate
         * @enum {string}
         */
        CaseSort: "dueDate" | "-dueDate" | "updatedAt" | "-updatedAt";
        CaseFields: {
            id: string;
            title: string;
            vendor: string;
            contractNo: string;
            milestone: string;
            /** @description The invoice amount. Null while no invoice states one. */
            amount: components["schemas"]["Money"] | null;
            /** Format: date */
            dueDate: string | null;
            status: components["schemas"]["CaseStatus"];
            /** @description The reviewer responsible for the case */
            owner: components["schemas"]["UserRef"] | null;
            /** @description Checks that did not pass */
            failed: number;
            /** @description Checks that could not be decided or found conflicting evidence */
            blocking: number;
            /** @description A file changed after the standing submission was made */
            needsRecheck: boolean;
            version: number;
            /** Format: date-time */
            updatedAt: string;
        };
        CaseSummary: components["schemas"]["CaseFields"];
        CasePage: {
            items: components["schemas"]["CaseSummary"][];
            total: number;
            /** @description False when the backend can only estimate the count */
            totalExact: boolean;
            page: number;
            pageSize: number;
        };
        /** @enum {string} */
        FileKind: "contract" | "terms" | "supplement" | "invoice" | "acceptance";
        CaseFile: {
            id: string;
            title: string;
            kind: components["schemas"]["FileKind"];
            /** @description Current version */
            version: number;
            /** Format: date */
            receivedAt: string;
            source: string;
        };
        FileVersion: {
            id: string;
            caseId: string;
            title: string;
            kind: components["schemas"]["FileKind"];
            version: number;
            currentVersion: number;
            /** Format: date */
            receivedAt: string;
            source: string;
            fragments: {
                /** @description Stable name of the place inside the file */
                key: string;
                /** @description Where a person finds it */
                locator: string;
                text: string;
            }[];
        };
        /** @description A pointer to one place in one version of a file. */
        EvidenceRef: {
            fileId: string;
            title: string;
            version: number;
            currentVersion: number;
            key: string;
            locator: string;
        };
        BasisVersion: {
            fileId: string;
            title: string;
            version: number;
            /** @description False when the file has a newer version */
            current: boolean;
        };
        /** @description A deterministic drill rule applied to the files. Not a legal or financial conclusion. */
        CheckResult: {
            rule: string;
            ruleVersion: number;
            title: string;
            /** @enum {string} */
            outcome: "pass" | "fail" | "unknown" | "conflict";
            detail: string;
            basis: components["schemas"]["EvidenceRef"][];
            /** @description What has to arrive before the rule can be decided, and who supplies it. */
            missing: {
                what: string;
                supplier: string;
            }[];
            /** @description Present when two sources state different values for the same thing. */
            conflict: {
                field: string;
                values: {
                    display: string;
                    ref: components["schemas"]["EvidenceRef"];
                }[];
            } | null;
        };
        /** @description A suggestion produced by a machine. It changes nothing until a person submits. */
        Proposal: {
            id: string;
            /** @enum {string} */
            source: "machine";
            /** Format: date-time */
            generatedAt: string;
            /** @enum {string} */
            suggestion: "submit" | "submit-as-exception" | "request-material";
            text: string;
            basis: components["schemas"]["BasisVersion"][];
            /** @description False when any file it was based on has a newer version */
            current: boolean;
        };
        ReviewRecord: {
            /** @enum {string} */
            kind: "submission" | "return" | "acceptance";
            by: components["schemas"]["UserRef"];
            /** Format: date-time */
            at: string;
            attemptId: string;
            /** @description Version of the case after this record */
            caseVersion: number;
            /** @enum {string} */
            conclusion?: "sufficient" | "exception";
            explanation?: string;
            proposalUse?: components["schemas"]["ProposalUse"];
            /** @description The machine proposal the person was responding to */
            proposalId?: string;
            basis?: components["schemas"]["BasisVersion"][];
        };
        /**
         * @description What the person did with the machine proposal. "none" when there was no proposal.
         * @enum {string}
         */
        ProposalUse: "adopted" | "amended" | "rejected" | "none";
        Case: components["schemas"]["CaseFields"] & {
            requester: string;
            files: components["schemas"]["CaseFile"][];
            /** @description Submissions, returns and the acceptance, oldest first. Nothing is overwritten. */
            records: components["schemas"]["ReviewRecord"][];
            /** @description What a submission made now would carry. The conclusion follows from the checks; the person does not choose it. */
            submission: {
                /** @enum {string} */
                conclusion: "sufficient" | "exception";
                explanationRequired: boolean;
                /** @description What may be said about the machine proposal. ["none"] when there is none; "adopted" is absent when the proposal was made on older material or disagrees with the checks. */
                proposalUses: components["schemas"]["ProposalUse"][];
                receiver: components["schemas"]["UserRef"];
                basis: components["schemas"]["BasisVersion"][];
            };
            /** @description The step this case is waiting for and who holds it. */
            next: {
                /** @enum {string} */
                step: "supply-material" | "submit" | "decide" | "recheck" | "pay-elsewhere";
                /** @description Null when the step is held outside this workbench or by nobody yet */
                owner: components["schemas"]["UserRef"] | null;
            };
            actions: components["schemas"]["Affordance"][];
        };
        SubmitInput: {
            caseId: string;
            expectedVersion: number;
            explanation: string;
            proposalUse: components["schemas"]["ProposalUse"];
        };
        AcceptInput: {
            caseId: string;
            expectedVersion: number;
            note?: string;
        };
        ReturnInput: {
            caseId: string;
            expectedVersion: number;
            reason: string;
        };
        SearchHit: {
            /** @enum {string} */
            kind: "case";
            id: string;
            title: string;
            context: string;
        };
        RuleViolation: {
            rule: string;
            ruleVersion: number;
            message: string;
            /** @description Who may grant an exception */
            exceptionOwner?: string;
            /** @description The object the violation is about */
            ref?: string;
        };
        UserRef: {
            id: string;
            name: string;
        };
        Problem: {
            /** @enum {string} */
            code: "unauthenticated" | "forbidden" | "not-found" | "conflict" | "rule-violation" | "invalid-input" | "unavailable";
            message: string;
            violations?: components["schemas"]["RuleViolation"][];
            /** @description On conflict */
            currentVersion?: number;
            changedBy?: components["schemas"]["UserRef"];
            /** Format: date-time */
            changedAt?: string;
            /** @description Who to ask when access is refused */
            contact?: string;
        };
        Meta: {
            /** @enum {string} */
            environment: "synthetic-demo" | "production";
            dataNotice: string;
            contractVersion: string;
            scenario: string;
        };
        "schemas-User": {
            id: string;
            name: string;
            /** @description A role name defined by the scenario */
            role: string;
            /** @description True when this user can be chosen as a demo identity */
            demoPersona: boolean;
        };
        "schemas-Affordance": {
            /** @description An action type defined by the scenario */
            type: string;
            allowed: boolean;
            violations: components["schemas"]["RuleViolation"][];
        };
        "schemas-ObjectRef": {
            /** @description An object kind defined by the scenario */
            kind: string;
            id: string;
            title: string;
        };
        "schemas-AuditEvent": {
            id: string;
            /** @description The object whose record this event belongs to */
            subjectId: string;
            /** Format: date-time */
            at: string;
            actor: components["schemas"]["UserRef"];
            /** @description An event type defined by the scenario */
            type: string;
            target: components["schemas"]["schemas-ObjectRef"];
            /** @description Version of the target after the event */
            targetVersion: number | null;
            attemptId: string | null;
            changes: {
                field: string;
                from: string | null;
                to: string | null;
            }[];
            /** @description Rules checked */
            rules: string[];
            note: string | null;
        };
        ActionResult: {
            attemptId: string;
            type: string;
            target: components["schemas"]["schemas-ObjectRef"];
            targetVersion: number;
            eventIds: string[];
            created: components["schemas"]["schemas-ObjectRef"][];
        };
        ActionAttempt: {
            attemptId: string;
            type: string;
            actor: components["schemas"]["UserRef"];
            /** Format: date-time */
            receivedAt: string;
            /**
             * @description For a job action, applied means the job ran to the end; whether each item took effect is in the job's items, not here.
             * @enum {string}
             */
            outcome: "applied" | "rejected" | "running";
            result?: components["schemas"]["ActionResult"];
            problem?: components["schemas"]["Problem"];
            jobId?: string;
        };
    };
    responses: {
        /** @description Why the request was not served */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Problem"];
            };
        };
        /** @description The action took effect */
        ActionApplied: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ActionResult"];
            };
        };
    };
    parameters: {
        caseId: string;
        /** @description Identity of this attempt. Sending the same key again returns the first result. */
        idempotencyKey: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getMeta: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Environment the backend reports */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Meta"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current actor */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listUsers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Users */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"][];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    search: {
        parameters: {
            query: {
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cases the actor may see */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchHit"][];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listCases: {
        parameters: {
            query?: {
                q?: string;
                status?: components["schemas"]["CaseStatus"];
                /** @description A user id, "me" for the current actor, or "none" for unassigned */
                owner?: string;
                dueFrom?: string;
                dueTo?: string;
                /** @description Required with amountMin or amountMax. Amounts in different currencies are not comparable. */
                currency?: string;
                /** @description In minor units of `currency` */
                amountMin?: number;
                /** @description In minor units of `currency` */
                amountMax?: number;
                sort?: components["schemas"]["CaseSort"];
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of cases */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CasePage"];
                };
            };
            422: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    getCase: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                caseId: components["parameters"]["caseId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Case with its files */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Case"];
                };
            };
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    listChecks: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                caseId: components["parameters"]["caseId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Check results */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckResult"][];
                };
            };
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    getProposal: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                caseId: components["parameters"]["caseId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The machine proposal for this case */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Proposal"];
                };
            };
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    listEvents: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                caseId: components["parameters"]["caseId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Audit events */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditEvent"][];
                };
            };
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    getFileVersion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                fileId: string;
                version: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description File version */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileVersion"];
                };
            };
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    submitForReview: {
        parameters: {
            query?: never;
            header: {
                /** @description Identity of this attempt. Sending the same key again returns the first result. */
                "Idempotency-Key": components["parameters"]["idempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitInput"];
            };
        };
        responses: {
            200: components["responses"]["ActionApplied"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    acceptReview: {
        parameters: {
            query?: never;
            header: {
                /** @description Identity of this attempt. Sending the same key again returns the first result. */
                "Idempotency-Key": components["parameters"]["idempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AcceptInput"];
            };
        };
        responses: {
            200: components["responses"]["ActionApplied"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    returnReview: {
        parameters: {
            query?: never;
            header: {
                /** @description Identity of this attempt. Sending the same key again returns the first result. */
                "Idempotency-Key": components["parameters"]["idempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReturnInput"];
            };
        };
        responses: {
            200: components["responses"]["ActionApplied"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    getActionAttempt: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attemptId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Attempt */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionAttempt"];
                };
            };
            404: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
}
