/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Meta: {
            /** @enum {string} */
            environment: "synthetic-demo" | "production";
            dataNotice: string;
            contractVersion: string;
            scenario: string;
        };
        UserRef: {
            id: string;
            name: string;
        };
        User: {
            id: string;
            name: string;
            /** @description A role name defined by the scenario */
            role: string;
            /** @description True when this user can be chosen as a demo identity */
            demoPersona: boolean;
        };
        RuleViolation: {
            rule: string;
            ruleVersion: number;
            message: string;
            /** @description Who may grant an exception */
            exceptionOwner?: string;
            /** @description The object the violation is about */
            ref?: string;
        };
        Affordance: {
            /** @description An action type defined by the scenario */
            type: string;
            allowed: boolean;
            violations: components["schemas"]["RuleViolation"][];
        };
        Problem: {
            /** @enum {string} */
            code: "unauthenticated" | "forbidden" | "not-found" | "conflict" | "rule-violation" | "invalid-input" | "unavailable";
            message: string;
            violations?: components["schemas"]["RuleViolation"][];
            /** @description On conflict */
            currentVersion?: number;
            changedBy?: components["schemas"]["UserRef"];
            /** Format: date-time */
            changedAt?: string;
            /** @description Who to ask when access is refused */
            contact?: string;
        };
        ObjectRef: {
            /** @description An object kind defined by the scenario */
            kind: string;
            id: string;
            title: string;
        };
        AuditEvent: {
            id: string;
            /** @description The object whose record this event belongs to */
            subjectId: string;
            /** Format: date-time */
            at: string;
            actor: components["schemas"]["UserRef"];
            /** @description An event type defined by the scenario */
            type: string;
            target: components["schemas"]["ObjectRef"];
            /** @description Version of the target after the event */
            targetVersion: number | null;
            attemptId: string | null;
            changes: {
                field: string;
                from: string | null;
                to: string | null;
            }[];
            /** @description Rules checked */
            rules: string[];
            note: string | null;
        };
        ActionResult: {
            attemptId: string;
            type: string;
            target: components["schemas"]["ObjectRef"];
            targetVersion: number;
            eventIds: string[];
            created: components["schemas"]["ObjectRef"][];
        };
        ActionAttempt: {
            attemptId: string;
            type: string;
            actor: components["schemas"]["UserRef"];
            /** Format: date-time */
            receivedAt: string;
            /**
             * @description For a job action, applied means the job ran to the end; whether each item took effect is in the job's items, not here.
             * @enum {string}
             */
            outcome: "applied" | "rejected" | "running";
            result?: components["schemas"]["ActionResult"];
            problem?: components["schemas"]["Problem"];
            jobId?: string;
        };
        JobItem: {
            ref: components["schemas"]["ObjectRef"];
            /** @enum {string} */
            status: "pending" | "applied" | "rejected";
            violations: components["schemas"]["RuleViolation"][];
        };
        Job: {
            id: string;
            attemptId: string;
            type: string;
            /** @enum {string} */
            status: "running" | "completed";
            total: number;
            done: number;
            items: components["schemas"]["JobItem"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
